// Catálogo inicial de géneros (lo administra el admin). Los DJs eligen de esta lista,
// así el filtro por género del index es consistente.
export const GENRE_SEED: readonly { slug: string; name: string }[] = [
  { slug: 'house', name: 'House' },
  { slug: 'deep-house', name: 'Deep House' },
  { slug: 'tech-house', name: 'Tech House' },
  { slug: 'techno', name: 'Techno' },
  { slug: 'melodic-techno', name: 'Melodic Techno' },
  { slug: 'hard-techno', name: 'Hard Techno' },
  { slug: 'minimal-deep-tech', name: 'Minimal Deep Tech' },
  { slug: 'minimal', name: 'Minimal' },
  { slug: 'progressive-house', name: 'Progressive House' },
  { slug: 'afro-house', name: 'Afro House' },
  { slug: 'organic-house', name: 'Organic House' },
  { slug: 'jackin-funky', name: 'Jackin & Funky' },
  { slug: 'nu-disco', name: 'Disco / Nu Disco' },
  { slug: 'indie-dance', name: 'Indie Dance' },
  { slug: 'bass-house', name: 'Bass House' },
  { slug: 'uk-garage', name: 'UK Garage' },
  { slug: 'drum-and-bass', name: 'Drum & Bass' },
  { slug: 'trance', name: 'Trance' },
  { slug: 'psytrance', name: 'Psytrance' },
  { slug: 'electro', name: 'Electro' },
  { slug: 'latin-house', name: 'Latin House' },
  { slug: 'guaracha', name: 'Guaracha' },
  { slug: 'reggaeton', name: 'Reggaetón' },
  { slug: 'crossover', name: 'Crossover' },
  { slug: 'open-format', name: 'Open Format' },
  { slug: 'hip-hop', name: 'Hip Hop' },
  { slug: 'electronica', name: 'Electrónica' },
];
