// Límites duros de la plataforma. El api es la autoridad; la web los usa para validar antes de enviar.

const MB = 1024 * 1024;

export const LIMITS = {
  user: {
    usernameMin: 3,
    usernameMax: 24,
    emailMax: 254,
    passwordMin: 10,
    adminPasswordMin: 12,
    passwordMax: 128,
  },
  profile: {
    slugMin: 3,
    slugMax: 40,
    slugChangeCooldownDays: 30,
    maxSlugRedirects: 5,
    displayNameMin: 2,
    displayNameMax: 60,
    taglineMax: 120,
    seoDescriptionMax: 160,
    cityMax: 60,
    whatsappDigitsMin: 8,
    whatsappDigitsMax: 15,
    statusReasonMax: 500,
    statusReasonMin: 10,
  },
  genres: { perProfileMin: 1, perProfileMax: 6, nameMin: 2, nameMax: 40 },
  members: { max: 6, nameMax: 60, roleMax: 80, descriptionMax: 400 },
  social: { perProfileMax: 10, perMemberMax: 6, urlMax: 500, labelMax: 30 },
  gallery: { max: 24, altMax: 125 },
  rider: { max: 20, nameMax: 60, noteMax: 80 },
  events: {
    upcomingMax: 30,
    storedMax: 100,
    titleMax: 80,
    venueMax: 90,
    cityMax: 60,
    ctaLabelMax: 20,
    ctaUrlMax: 500,
    maxDaysAhead: 730,
  },
  texts: { multilineMaxLines: 8 },
  form: { labelMax: 60, placeholderMax: 80, activeFieldsMax: 20 },
  booking: {
    payloadMaxBytes: 16_384,
    textareaMaxLines: 30,
    perIpPerProfilePerDay: 5,
    perIpPerDay: 20,
    perProfilePerDay: 50,
    tokenMinAgeMs: 2_000,
    tokenMaxAgeMs: 2 * 60 * 60 * 1000,
    inboxPageSize: 20,
    inboxPageSizeMax: 100,
    whatsappMessageMax: 1_800,
  },
  upload: {
    maxBytes: 10 * MB,
    maxInputPixels: 40_000_000,
    minSidePx: 200,
    clientMaxLongEdgePx: 2560,
    allowedMimes: ['image/jpeg', 'image/png', 'image/webp'] as const,
    quotaUnapproved: { assets: 20, bytes: 25 * MB },
    quotaApproved: { assets: 100, bytes: 100 * MB },
    minFreeDiskBytes: 5 * 1024 * MB,
    orphanTtlHours: 24,
  },
  ticket: { messageMax: 3000, nameMax: 80, subjectMax: 120, resolutionMax: 3000 },
  /** Listas paginadas del admin (usuarios, solicitudes, PQRS, auditoría, perfiles). */
  admin: { pageSizeDefault: 20, pageSizeMax: 100 },
  legalInfo: { legalNameMax: 120, docNumberMax: 20, addressMax: 200, phoneMax: 20, phonesMax: 3 },
  retention: {
    bookingMonths: 12,
    auditMonths: 24,
    resetTokenMinutes: 30,
    verifyTokenHours: 48,
    tempPasswordHours: 72,
    draftIdleDays: 30,
    /** Registro del art. 53 de un perfil borrado: se conserva y luego se purga. */
    legalInfoMonths: 12,
    unverifiedUserDays: 14,
  },
} as const;
